cc_binary(
  name = "brres-analyse",
  srcs = ["main.cc"],
  deps = [
    "//src/lib/bytes",
    "//src/lib/formats/brres",
    "//src/lib/formats/brres/index_group",
    "//src/lib/formats/mdl0",
    "//src/lib",
    "//src/lib/fs",
    "@abseil-cpp//absl/flags:flag",
    "@abseil-cpp//absl/log",
    "@abseil-cpp//absl/log:check",
    "@abseil-cpp//absl/strings",
  ],
)