cc_binary(
  name = "brres-analyse",
  srcs = ["main.cc"],
  deps = [
    "//src/lib/bytes",
    "//src/lib/formats/brres",
    "//src/lib/formats/brres/index_group",
    "//src/lib/formats/mdl0",
    "@com_google_absl//absl/flags:flag",
    "@com_google_absl//absl/flags:parse",
    "@com_google_absl//absl/log",
    "@com_google_absl//absl/log:check",
    "@com_google_absl//absl/strings",
  ],
)