cc_binary(
  name = "u8",
  srcs = ["main.cc"],
  deps = [
    "//src/lib/bytes",
    "//src/lib/formats/u8",
    "//src/lib/compression/yaz0",
    "@com_google_absl//absl/log",
    "@com_google_absl//absl/log:check",
  ],
)