cc_binary(
  name = "u8",
  srcs = ["main.cc"],
  deps = [
    "//src/lib/bytes",
    "//src/lib/fs",
    "//src/lib/formats/u8",
    "//src/lib/compression/yaz0",
    "@abseil-cpp//absl/log",
    "@abseil-cpp//absl/log:check",
    "@abseil-cpp//absl/log:flags",
    "@abseil-cpp//absl/flags:parse",
  ],
)